[build] 
  publish = "dist"
  command = "pnpm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."


[dev] 
  publish = "dist"
  command = "pnpm run dev"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
